### ISSUE TITLE
BITSHUFFLE data corruption

### ISSUE THREAD

**Issue by 2-5** [Blosc/python-blosc#220] opened 2020-01-29 00:04 UTC
Windows 10/Python 3.7.1/64 bit/Blosc 1.8.3

Blosc corrupts the file inside the .zip archive when compressing with `BITSHUFFLE`

https://www.dropbox.com/s/dbxxq4ej0cyfg3y/blosc_corrupt.zip (110 MB)

```python
import blosc

data = open("blosc_corrupt.data", "rb").read()

compressed = blosc.compress(data, shuffle=blosc.BITSHUFFLE)
uncompressed = blosc.decompress(compressed)

assert uncompressed == data  # FAILS
```

**Comment by FrancescAlted** [comment] 2020-02-05 08:56
Yes, I can reproduce this.  Will try to come with a fix as soon as possible.

**Comment by FrancescAlted** [comment] 2020-02-17 14:03
This has something to do with the input size not being divisible by the default `typesize` in blosc (currently 8).  Using a typesize of 4:

```
compressed = blosc.compress(data, typesize=4, shuffle=blosc.BITSHUFFLE)
```

this works perfectly.

Curiously enough, a C program cannot detect the issue:

```
#include <stdio.h>
#include <blosc.h>


int main() {
  FILE *fp;
  fp = fopen("/tmp/blosc_corrupt.data", "r");
  fseek(fp, 0L, SEEK_END);
  int size = (int)ftell(fp);
  rewind(fp);

  int64_t *data = malloc(size);
  int64_t *data_out = malloc(size + BLOSC_MIN_HEADER_LENGTH);
  int64_t *data_dest = malloc(size);

  fread(data, size, 1, fp);

  int32_t *final_values = (int32_t*) data;
  printf("final value: %d\n", final_values[(229230660 - 4) / 4]);

  printf("Blosc version info: %s (%s)\n", BLOSC_VERSION_STRING, BLOSC_VERSION_DATE);

  blosc_set_nthreads(1);

  /* Compress with clevel=5 and shuffle active  */
  int isize = size;
  int osize = size + BLOSC_MIN_HEADER_LENGTH;
  int csize = blosc_compress(9, 2, sizeof(int64_t), isize, data, data_out, osize);
  if (csize == 0) {
    printf("Buffer is uncompressible.  Giving up.\n");
    return 1;
  }
  else if (csize < 0) {
    printf("Compression error.  Error code: %d\n", csize);
    return csize;
  }

  printf("Compression: %d -> %d (%.1fx)\n", isize, csize, (1.*isize) / csize);
  FILE *fout = fopen("/tmp/blosc_corrupt_compressed.data", "w");
  fwrite(data_out, csize, 1, fout);
  fclose(fout);

  /* Decompress  */
  int dsize = blosc_decompress(data_out, data_dest, isize);
  if (dsize < 0) {
    printf("Decompression error.  Error code: %d\n", dsize);
    return dsize;
  }

  printf("Decompression succesful!\n");

  for(int i = 0; i < size / sizeof(int64_t); i++){
    if(data[i] != data_dest[i]) {
      printf("Decompressed data differs from original!\n");
      return -1;
    }
  }

  printf("Succesful roundtrip!\n");
  *final_values = (int32_t*) data_dest;
  printf("final value: %d\n", final_values[(229230660 - 4) / 4]);
  return 0;
}
```

so clearly the problem seems to be in the Python wrapper.  Wierd, still investigating...

**Comment by FrancescAlted** [comment] 2020-02-18 13:45
Finally the problem was in the c-blosc library, but not exposed by the code above.  The fix is in its own branch: https://github.com/Blosc/c-blosc/commit/f44663e6800cac69b743bc331c733afb4b05bcae.  The reason for not merging it in master yet is that the bitshuffling algorithm applies differently and it may be possible that it is not backwards compatible.

**Comment by 2-5** [comment] 2020-02-21 14:03
The documentation doesn't say anything about buffer size being required to be a multiple of typesize. If arbitrary buffer sizes are not a supported use case, blosc should throw an exception for them.

This bug shattered my confidence in blosc (sorry), especially after I've seen that there was a similar bug in the past. It took me many hours to track this down. This is my workaround for now:

```python
kwargs = dict(typesize=8, clevel=9, cname="zlib")
output_data = blosc.compress(change_data, shuffle=blosc.BITSHUFFLE, **kwargs)
if blosc.decompress(output_data) != change_data:
    print("*** BLOSC BITSHUFFLE COMPRESSION CORRUPTED DATA. USING SHUFFLE INSTEAD ***")
    output_data = blosc.compress(change_data, shuffle=blosc.SHUFFLE, **kwargs)
    assert blosc.decompress(output_data) == change_data
```

I strongly suggest adding some sort of checksum to blosc (I see it's a blosc-2 proposal).

**Comment by FrancescAlted** [comment] 2020-02-21 15:09
I understand.  A possible workaround is to avoid passing buffersizes that are not divisible by the `typesize` which by the default is 8.  In these cases, probably what you want is to pass `typesize=1` and bitshuffle will act one every byte, avoiding the leftover block issue.

**Closed** 2020-02-23 11:41 UTC
Labels: bug

**Comment by FrancescAlted** [comment] 2020-02-23 11:44
After thinking more about this, I came with a solution for [fixing this right in c-blosc](https://github.com/Blosc/python-blosc/issues/220) without any forward-compatibility problems.  This still needs some testing.

**Comment by FrancescAlted** [comment] 2020-02-23 12:10
The fix in c-blosc has been ported to python-blosc and a new test has been added in commit fe96f5e.  This seems to work well.
